services:
  db:
    image: mysql:8.0
    container_name: mysql-bahontobungku
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rasya123
      MYSQL_DATABASE: bahontobungku
      MYSQL_USER: bahontobungku_user
      MYSQL_PASSWORD: bahontobungku123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /home/rasyarhmt/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend-bahontobungku
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend-bahontobungku
    restart: always
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
